webtalk_init -webtalk_dir C:/project/vivadoProject/2017_2_17_HDB3_encode/2017_2_17_HDB3_encode1/QM_XC7A35TFTG256.sim/sim_1/behav/xsim.dir/TOP_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sat Feb 18 16:52:00 2017" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2016.4 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "1733598" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "a4c29401ceec522b9e9355ba1730b798" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "85023478c8774591a5e1aabf500d4908" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "8" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-4200U CPU @ 1.60GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2295 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "2 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.01_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "9568_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2966050183 -regid "" -xml C:/project/vivadoProject/2017_2_17_HDB3_encode/2017_2_17_HDB3_encode1/QM_XC7A35TFTG256.sim/sim_1/behav/xsim.dir/TOP_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/project/vivadoProject/2017_2_17_HDB3_encode/2017_2_17_HDB3_encode1/QM_XC7A35TFTG256.sim/sim_1/behav/xsim.dir/TOP_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/project/vivadoProject/2017_2_17_HDB3_encode/2017_2_17_HDB3_encode1/QM_XC7A35TFTG256.sim/sim_1/behav/xsim.dir/TOP_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
